version: '3.8'

services:
  web:
    build:
      context: ./app
    container_name: php-web-app
    volumes:
      - ./app:/var/www/html/
    ports:
      - "57000:80"
    depends_on:
      - db
    networks:
      - app-network
  
  v2:
    build:
      context: ./v2
    container_name: php-web-app-v2
    volumes:
      - ./v2:/var/www/html/
    ports:
      - "57001:80"
    depends_on:
      - db
    networks:
      - app-network


  db:
    build:
      context: ./db
    container_name: mysql-db
    volumes:
      - ./db/db_data:/var/lib/mysql:rw
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      - ./db/dump.sql:/data/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: busreservation
      MYSQL_USER: sample
      MYSQL_PASSWORD: root
    ports:
      - "37060:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 880:80
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: busreservation
      MYSQL_USER: sample
      MYSQL_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
